# Uncomment this line to define a global platform for your project

#官方Cocoapods的源/Users/eyrefree/Documents/XWS/WRCycleScrollView/WRCycleScrollViewDemo/WRCycleScrollViewDemo.xcodeproj
#source 'https://github.com/CocoaPods/Specs.git'

#本地私有源
#source 'https://git.oschina.net/scx/JLSpecs.git'

# 本项目地址
#source https://github.com/wangrui460

# 修改过得第三方库


platform :ios, '8.0'
use_frameworks!

target 'WRCycleScrollViewDemo' do
    pod 'Kingfisher', '4.10.1'
    pod 'WRNavigationBar_swift', :git => 'https://github.com/EFRenovation/WRNavigationBar_swift.git'
end
